# Generated by Django 5.2.1 on 2025-06-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('learnt', models.TextField()),
                ('built', models.TextField()),
                ('thoughts', models.TextField()),
                ('tomorrow', models.TextField()),
            ],
        ),
    ]
