# Generated by Django 5.2.1 on 2025-06-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Available',
        ),
    ]
